### ISSUE TITLE
mtModel is undefined when using Mongoose 4.0.3

### ISSUE THREAD

**Issue by simukka** [jraede/mongoose-multitenant#10]
node v0.12.4
mongoose 4.0.3

Reproduction:
1. start node `node`
2. > `var mongoose = require('mongoose');`
3. > `require('mongoose-multitenant');`
4. > `mongoose.mtModel`
undefined

**Comment by jraede** [comment]
I probably won't be updating this for 4.x support, since I no longer use it in my projects. But you're more than welcome to submit a PR. Thanks

**Comment by devel-pa** [comment]
Looks like it's working with 4.2

**Comment by vanm** [comment]
@jraede @devel-pa Any plans to submit a PR to merge your fork?

https://github.com/jraede/mongoose-multitenant/compare/master...apikay:master

The multitenant npm doesn't work with 4.x without moving `mongoose` to peerDependencies and passing through a reference to mongoose as @devel-pa has done in that fork.

**Comment by devel-pa** [comment]
My changes are done in JS file, so not quite compat with what is here, but if needed I can do it in coffee file and align with this. I'm also passing a reference of mongoose as is easier to use this lib in conjunction with others.
There should be another incompatibility, I've changed also `mongoose-schema-extend`

**Comment by zadam** [comment]
@jraede Shouldn't this be reopened since this is still a problem? I stumbled upon this issue by chance after hours of trying to get it working ... unfortunately nowhere (except here in the closed issue) it is indicated that project is simply not compatible with Mongoose 4.X :-/
