### ISSUE TITLE
mongoose package is installed when you have different versions

### ISSUE THREAD

**Issue by DanilloCorvalan** [jraede/mongoose-multitenant#4]
This causes an error where it adds the complementary methods such as ```mtModel()``` to the mongoose package inside this lib. Instead of adding it to the mongoose provided in the source. I noticed that it creates a mongoose folder inside node_modules/mongoose. So if you already have a mongoose version installed and if it is different from what specified in this lib you will face some problems like ```mtModel() not found```

**Comment by anoopsinghbayes** [comment]
we can use peerDependencies[http://blog.nodejs.org/2013/02/07/peer-dependencies/] for this
