### ISSUE TITLE
refs/populate works only with ObjectId

### ISSUE THREAD

**Issue by maxcnunes** [jraede/mongoose-multitenant#8]
I took some time to figure out the "refs/populate" works only with `ObjectId`. I was using a similar configuration from mongoose [populate example](http://mongoosejs.com/docs/populate.html) which `_id` is a `Number` and couldn't make the populate work.

Seems the implementation accepts only refs to `ObjectId` ([here](https://github.com/jraede/mongoose-multitenant/blob/master/index.js#L38) and [here](https://github.com/jraede/mongoose-multitenant/blob/master/index.js#L45)).

To make my populate work I changed my refs to `ObjectId`. But would be awesome if the refs could also work with other types.

In case there is no plan to do this change. Would be good to make clear in the documentation the refs works only with ObjectId.

**Comment by jraede** [comment]
Hey, sorry it's taken so long to respond. I have no plans to add additional features at the moment but yes, it's a good idea to add that to the readme. I'll do it in the next release
